#' Read Formant file
#'
#' Read Formant file generated by Praat in SSFF or data frame format.
#'
#' @param filename String giving the path to a Formant file or a directory of
#' Formant files. Alternatively a vector of strings giving the paths to Formant
#' files.
#' @param output String giving the desired output format. Should be either
#' `ssff` (default) for a list with the Simple Signal File Format or `df` for a
#' data frame.
#' @param ext String giving the file extension for Formant files; default is
#' `.Formant`. Only used if `filename` is a directory.
#' @param times Optional numeric vector giving the times to return signal
#' values from. Default is `NULL`.
#' @param returnBw Boolean; should formant bandwidths be returned? Default is
#' `FALSE`.
#' @param returnIntensity Boolean; should intensity values be returned?
#' Default is `FALSE`.
#' @param toFile Boolean; if the output format is `ssff`, should these
#' objects be saved to disk as individual files? Default is `FALSE`.
#' @param outputDir String giving the location of the output directory of
#' SSFF files when `toFile = TRUE`. Default is to use the current working
#' directory.
#' @param outputExt String giving the file extension of SSFF files when
#' `toFile = TRUE`. Default is `.fmt`.
#'
#' @returns A list of class `AsspDataObj` or data frame depending on the value
#' of `output`.
#' @export
#'
#' @examples
#' datapath <- system.file('extdata', package='praatutils')
#' soundFile <- paste0(datapath, '/1.Formant')
#' fmt <- readFormant(soundFile)
readFormant <- function(filename, output = 'ssff', ext = '.Formant', times = NULL,
                        returnBw = FALSE, returnIntensity = FALSE,
                        toFile = FALSE, outputDir = getwd(),
                        outputExt = '.fmt') {

  if (!output %in% c('df', 'ssff')) stop(
    'output should be either df or ssff')

  if (any(dir.exists(filename))) filename <-
      list.files(filename, pattern = ext)
  if (length(filename) > 1 & output == 'ssff' & !toFile) stop(
    'When processing multiple files with ssff output, toFile must be TRUE')

  p <- reticulate::import('parselmouth')

  for (f in filename) {
    fm <- p$read(f)
    tmp <- formant2table(fm, f, returnBw, returnIntensity)

    if (output == 'ssff') {
      ado <- formant2ssff(fm, tmp, returnBw, returnIntensity)
      if (!toFile) {
        out <- ado
      } else {
        wrassp::write.AsspDataObj(ado, file.path(outputDir,
                                                 gsub(ext, outputExt, f)))
      }
    } else if (output == 'df') {
      if ('out' %in% ls()) {
        out <- rbind(out, tmp)
      } else {
        out <- tmp
      }
    }
  }

  if (!toFile) return(out)

}
