#' Read Intensity file
#'
#' Read Intensity file generated by Praat in SSFF or data frame format.
#'
#' @param filename String giving the path to a Intensity file or a directory
#' of Intensity files. Alternatively a vector of strings giving the paths to
#' Intensity files.
#' @param output String giving the desired output format. Should be either
#' `ssff` (default) for a list with the Simple Signal File Format or `df` for a
#' data frame.
#' @param ext String giving the file extension for Intensity files; default is
#' `.Intensity`. Only used if `filename` is a directory.
#' @param times Optional numeric vector giving the times to return signal
#' values from. Default is `NULL`.
#' @param toFile Boolean; if the output format is `ssff`, should these
#' objects be saved to disk as individual files? Default is `FALSE`.
#' @param outputDir String giving the location of the output directory of
#' SSFF files when `toFile = TRUE`. Default is to use the current working
#' directory.
#' @param outputExt String giving the file extension of SSFF files when
#' `toFile = TRUE`. Default is `.rms`.
#'
#' @returns A list of class `AsspDataObj` or data frame depending on the value
#' of `output`.
#' @export
#'
#' @examples
#' datapath <- system.file('extdata', package='praatutils')
#' soundFile <- paste0(datapath, '/1.Intensity')
#' rms <- readIntensity(soundFile)
readIntensity <- function(filename, output = 'ssff', ext = '.Intensity',
                            times = NULL, toFile = FALSE, outputDir = getwd(),
                            outputExt = '.rms') {

  if (!output %in% c('df', 'ssff')) stop(
    'output should be either df or ssff')

  if (any(dir.exists(filename))) filename <-
      list.files(filename, pattern = ext)
  if (length(filename) > 1 & output == 'ssff' & !toFile) stop(
    'When processing multiple files with ssff output, toFile must be TRUE')

  if (output == 'df') out <- data.frame(file = NULL, t = NULL, hnr = NULL)

  p <- reticulate::import('parselmouth')

  for (f in filename) {
    rms <- p$read(f)

    if (output == 'ssff') {
      ado <- intensity2ssff(rms)
      if (!toFile) {
        out <- ado
      } else {
        wrassp::write.AsspDataObj(ado, file.path(outputDir,
                                                 gsub(ext, outputExt, f)))
      }
    } else if (output == 'df') {
      tmp <- intensity2df(rms, f, times)
      out <- rbind(out, tmp)
    }
  }

  if (!toFile) return(out)

}
