#' Read Pitch file
#'
#' Read Pitch file generated by Praat in SSFF or data frame format.
#'
#' @param filename String giving the path to a Pitch file or a directory
#' of Pitch files. Alternatively a vector of strings giving the paths to
#' Pitch files.
#' @param output String giving the desired output format. Should be either
#' `ssff` (default) for a list with the Simple Signal File Format or `df` for a
#' data frame.
#' @param ext String giving the file extension for Pitch files; default is
#' `.Pitch`. Only used if `filename` is a directory.
#' @param times Optional numeric vector giving the times to return signal
#' values from. Default is `NULL`.
#' @param toFile Boolean; if the output format is `ssff`, should these
#' objects be saved to disk as individual files? Default is `FALSE`.
#' @param outputDir String giving the location of the output directory of
#' SSFF files when `toFile = TRUE`. Default is to use the current working
#' directory.
#' @param outputExt String giving the file extension of SSFF files when
#' `toFile = TRUE`. Default is `.f0`.
#'
#' @returns A list of class `AsspDataObj` or data frame depending on the value
#' of `output`.
#' @export
#'
#' @examples
#' datapath <- system.file('extdata', package='praatutils')
#' soundFile <- paste0(datapath, '/1.Pitch')
#' pit <- readPitch(soundFile)
readPitch <- function(filename, output = 'ssff', ext = '.Pitch', times = NULL,
                      toFile = FALSE, outputDir = getwd(), outputExt = '.f0') {

  if (!output %in% c('df', 'ssff', 'candidates')) stop(
    'output should be either df, ssff, or candidates')

  if (any(dir.exists(filename))) filename <-
      list.files(filename, pattern = ext)
  if (length(filename) > 1 & output == 'ssff' & !toFile) stop(
    'When processing multiple files with ssff output, toFile must be TRUE')

  if (output == 'df') out <- data.frame(file = NULL, t = NULL, f0 = NULL)
  if (output == 'candidates') out <- data.frame(
    file = NULL, frame = NULL, t = NULL, frequency = NULL, strength = NULL)

  p <- reticulate::import('parselmouth')

  for (f in filename) {
    pit <- p$read(f)

    if (output == 'ssff') {
      ado <- pitch2ssff(pit)
      if (!toFile) {
        out <- ado
      } else {
        wrassp::write.AsspDataObj(ado, file.path(outputDir,
                                                 gsub(ext, outputExt, f)))
      }
    } else if (output == 'df') {
      tmp <- pitch2df(pit, f, times)
      out <- rbind(out, tmp)
    } else if (output == 'candidates') {
      tmp <- pitch2cand(pit, f)
      out <- rbind(out, tmp)
    }
  }

  if (!toFile) return(out)

}
